version: '2.1'

services:
  http:
    container_name: ${CONTAINER_PREFIX}apache
    image: knowgod/apache2:2.4.10
    volumes:
        - ${LOG_ROOT}:/var/log
        - http_a2-vol:/etc/apache2
        - ${HTTPD_DOCUMENT_ROOT}:/var/www
    depends_on:
        - php70
    links:
        - php70:php70.${HOST}
    networks:
        - ${NETWORK_NAME}

  php70:
    container_name: ${CONTAINER_PREFIX}php70
    image: knowgod/php-fpm:7.0
    volumes:
        - ${LOG_ROOT}:/var/log
        - php_70-vol:/etc/php
        - composer_70-vol:/home/composer/.composer
        - ~/.ssh/${SSH_KEY}:/home/composer/.ssh/id_rsa
        - ~/.ssh/known_hosts:/home/composer/.ssh/known_hosts
        - ${HTTPD_DOCUMENT_ROOT}:/var/www
    links:
        - db:db.${HOST}
        - es24:es24.${HOST}
    networks:
        - ${NETWORK_NAME}

  es24:
    container_name: ${CONTAINER_PREFIX}elastic
    image: knowgod/elasticsearch:2.4.2
    volumes:
        - es24-vol:/usr/share/elasticsearch/data
    depends_on:
        - db
    networks:
        - ${NETWORK_NAME}

  db:
    container_name: ${CONTAINER_PREFIX}mysql5.7
    image: knowgod/ubuntu-mysql:5.7
    environment:
        ENV DB_USER: magento
        ENV DB_PASS: tester1
    volumes:
        - ${LOG_ROOT}:/var/log
        - data_mysql-vol:/var/lib/mysql
    networks:
        - ${NETWORK_NAME}

volumes:
  data_mysql-vol:
  http_a2-vol:
  php_55-vol:
  php_70-vol:
  composer_70-vol:
  es24-vol:

networks:
  ${NETWORK_NAME}:
    driver: bridge
