# Add the following records to your /etc/hosts
# 172.0.10.2    db.magento-local.com
# 172.0.10.3    php.magento-local.com
# 172.0.10.4    magento-local.com

version: '2'

services:
  db:
    container_name: mageloc-db
    image: mariadb:10.1.16
    networks:
      default:
        ipv4_address: 172.00.10.2
    environment:
        MYSQL_USER: root
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 172.00.10.0/24
        gateway: 172.00.10.1

