version: '2.1'

services:
  http:
    container_name: ${CONTAINER_PREFIX}a24
    image: sergeyzskw/apache2
    volumes:
        - ${LOG_ROOT}:/var/log
        - http_a2-vol:/etc/apache2
        - ${HTTPD_DOCUMENT_ROOT}:/var/www
    depends_on:
        - php70
    links:
        - php70:php70.${HOST}
    networks:
        - ${NETWORK_NAME}

  php70:
    container_name: ${CONTAINER_PREFIX}php70
    image: sergeyzskw/php:7.0-fpm
    volumes:
        - ${LOG_ROOT}:/var/log
        - php_70-vol:/etc/php
        - composer_70-vol:/home/composer/.composer
        - ~/.ssh/${SSH_KEY}:/home/composer/.ssh/id_rsa
        - ~/.ssh/known_hosts:/home/composer/.ssh/known_hosts
        - ${HTTPD_DOCUMENT_ROOT}:/var/www
    links:
        - db:db.${HOST}
    networks:
        - ${NETWORK_NAME}

  db:
    container_name: ${CONTAINER_PREFIX}db
    image: mariadb
    environment:
        ENV DB_USER: magento
        ENV DB_PASS: tester1
    volumes:
        - ${LOG_ROOT}:/var/log
        - data_mariadb-vol:/var/lib/mysql
    networks:
        - ${NETWORK_NAME}

volumes:
  data_mariadb-vol:
  http_a2-vol:
  php_55-vol:
  php_70-vol:
  composer_70-vol:

networks:
  pon-tier:
    driver: bridge
