# Add the following records to your /etc/hosts
# Note*: IP can be different
# 
# 172.18.0.2	dev.db.local.com db.local.com
# 172.18.0.3	dev.php.local.com php.local.com dev.php55.local.com php55.local.com
# 172.18.0.4	local.com

version: '2'

services:
  http:
    container_name: local-httpd
    image: sergeyzskw/apache2
    volumes:
        - ${LOG_ROOT}:/var/log
        - http_a2-vol:/etc/apache2
        - ${HTTPD_DOCUMENT_ROOT}:/var/www
    depends_on:
        - php55
    links:
        - php55:php.${HOST}
        - php55:dev.php.${HOST}
        - php55:php55.${HOST}
        - php55:dev.php55.${HOST}

  php55:
    container_name: local-php55
    image: sergeyzskw/php:5.5-fpm
    volumes:
        - ${LOG_ROOT}:/var/log
        - php_55-vol:/etc/php5
        - exec_composer-vol:/home/composer/.composer
        - ~/.ssh/${SSH_KEY}:/home/composer/.ssh/id_rsa
        - ~/.ssh/known_hosts:/home/composer/.ssh/known_hosts
        - ${HTTPD_DOCUMENT_ROOT}:/var/www
    depends_on:
        - db
    links:
        - db:db.${HOST}
        - db:dev.db.${HOST}

  db:
    container_name: local-db
    image: mariadb
    environment:
        MYSQL_USER: root
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
        - ${LOG_ROOT}:/var/log
        - data_mariadb-vol:/var/lib/mysql

volumes:
  data_mariadb-vol:
  http_a2-vol:
  php_55-vol:
  exec_composer-vol:

