# Add the following records to your /etc/hosts
# 172.0.10.2    db.srgz-local.com
# 172.0.10.3    php.srgz-local.com php56.srgz-local.com
# 172.0.10.100  Your-Host-Name1, You-Host-Name2, etc...

version: '2'

services:
  http:
    container_name: srgzloc-httpd
    image: httpd:2.4.23
    networks:
      default:
        ipv4_address: 172.0.10.100
    volumes:
        - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
        - ./httpd/extra/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
        - ./magento-local.com/:/var/www/html/magento-local.com
  db:
    container_name: srgzloc-db
    image: mariadb:10.1.16
    networks:
      default:
        ipv4_address: 172.0.10.2
    environment:
        MYSQL_USER: root
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
        - dbdata:/var/lib/mysql

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 172.0.10.0/24
        gateway: 172.0.10.1

volumes:
  dbdata:
    driver: local

