# Add the following records to your /etc/hosts
# 172.0.10.2    db.<basehost>.com
# 172.0.10.3    php.<basehost>.com php55.<basehost>.com
# 172.0.10.100  Your-Host-Name1, You-Host-Name2, etc...

version: '2'

services:
  http:
    container_name: ${USER}local-httpd
    image: sergeyzskw/apache2
    volumes:
        - http_a2-vol:/etc/apache2
        - ${HTTPD_DOCUMENT_ROOT}:/var/www
    depends_on:
        - php55fpm
    links:
        - php55fpm:php.${HOST}
        - php55fpm:dev.php.${HOST}
        - php55fpm:php55.${HOST}
        - php55fpm:dev.php55.${HOST}

  php55fpm:
    container_name: ${USER}local-php55fpm
    image: sergeyzskw/php:5.5-fpm
    volumes:
        - exec_php55fpm-vol:/etc/php5
        - exec_composer-vol:/home/composer/.composer
        - ~/.ssh/${SSH_KEY}:/home/composer/.ssh/id_rsa
        - ~/.ssh/known_hosts:/home/composer/.ssh/known_hosts
        - ${HTTPD_DOCUMENT_ROOT}:/var/www
    depends_on:
        - db
    links:
        - db:db.${HOST}
        - db:dev.db.${HOST}

  db:
    container_name: ${USER}local-db
    image: mariadb
    environment:
        MYSQL_USER: root
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
        - data_mariadb-vol:/var/lib/mysql

volumes:
  data_mariadb-vol:
  http_a2-vol:
  exec_php55fpm-vol:
  exec_composer-vol:

