# Add the following records to your /etc/hosts
# 172.0.10.2    db.srgz-local.com
# 172.0.10.3    php.srgz-local.com php56.srgz-local.com
# 172.0.10.100  Your-Host-Name1, You-Host-Name2, etc...

version: '2'

services:
  http:
    container_name: srgzloc-httpd
    image: sergeyzskw/apache2
    volumes:
        - a2conf:/etc/apache2
  db:
    container_name: srgzloc-db
    image: mariadb
    environment:
        MYSQL_USER: root
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
        - data:/var/lib/mysql

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 172.0.10.0/24
        gateway: 172.0.10.1

volumes:
  data:
    driver: local
  a2conf:
    driver: local


